### ISSUE TITLE
Custom datasets

### ISSUE THREAD

**Issue by yinyiyu** [Ha0Tang/XingGAN#3]
Thanks for your excellent work. I want to conduct experiments on my own dataset. May I ask how to prepare my own dataset.

**Comment by Ha0Tang** [comment]
Hi, you can make similar data preprocess (e.g., data split, pose estimation, and heatmap generation). After that, you can train the models on your own datasets. Hope it will be helpful for you.

**Comment by yinyiyu** [comment]
Thank you for your reply. I found seven folders and four CSV files in each dataset. I think I would need to have a similar structure if I were to train this model on my own data set, and I'm not very clear about what the contents is and how the contents of each folder are obtained. Could you please give me a more detailed explanation,thanks！

**Comment by Ha0Tang** [comment]
Take the market dataset for an example, `market-pairs-train.csv`, and `market-pairs-test.csv` is training and test split, in which each line consists of a pair of two images (i.e., a source image and target image); `market-annotation-train.csv`, and `market-annotation-train.csv` are the extracted keypoints files which can be obtained by using [OpenPose](https://github.com/ZheC/Realtime_Multi-Person_Pose_Estimation). For more details about how to prepare the datasets, please refer [here](https://github.com/tengteng95/Pose-Transfer#notes-1).

**Comment by yinyiyu** [comment]
Thank you for your reply. I will try it according to your instructions
