### ISSUE TITLE
Some question about the SSIM metric 

### ISSUE THREAD

**Issue by zympsyche** [Ha0Tang/XingGAN#5]
Thanks for your novel work. When I calculated the SSIM metric, it's a little lower than the value that in the paper.
Here are the results that I obtained.
Market1501 dataset
![image](https://user-images.githubusercontent.com/32486130/101738511-34b1b680-3b01-11eb-9193-e31d52b31f37.png)

Some visual results that obtained with the pretrained model.
/0265_c6s1_056351_01.jpg___0265_c3s1_062642_05.jpg_vis.jpg
![image](https://user-images.githubusercontent.com/32486130/101739489-8b6bc000-3b02-11eb-8731-a74400221140.png)
1322_c3s3_035678_02.jpg___1322_c4s5_061435_01.jpg_vis.jpg
![image](https://user-images.githubusercontent.com/32486130/101739510-9292ce00-3b02-11eb-8724-6aea1c3fb53e.png)

I don't know where I got it wrong. 
Thanks for your time.

**Comment by Ha0Tang** [comment]
Hi, it is really strange to obtain such an unsatisfying result. Do you make any modifications to the original code? I could not tell where is wrong at the moment since too little information is provided.
