### ISSUE TITLE
How to visualize the pose map?

### ISSUE THREAD

**Issue by pumpkinnan97** [Ha0Tang/XingGAN#6]
Thanks for your novel work. It helps me a lot! And I wonder how to visualize the pose map as the figure shown in your paper? I can't find the visualization process in this repo. 

<img width="105" alt="截屏2021-01-06 下午5 09 49" src="https://user-images.githubusercontent.com/23496568/103750666-137db080-5042-11eb-8758-0d66eb1582bc.png">

**Comment by Ha0Tang** [comment]
Please refer to [this line](https://github.com/Ha0Tang/XingGAN/blob/a31c5c611b74b68c7a3b703ea53c8f525f1dbd91/models/XingGAN.py#L242).
