### ISSUE TITLE
Start point

### ISSUE THREAD

**Issue by Eliot04** [Ha0Tang/XingGAN#7]
Hi Hao

I'm trying to download the images but keep getting the following error:

Forbidden

You don't have permission to access /~hao.tang/uploads/models/XingGAN/ on this server.
Apache/2.4. .... Server at disi.unitn.it Port 80

May you please help where might be the problem?

**Comment by Ha0Tang** [comment]
What command line did you use to download the data?

**Comment by Ha0Tang** [comment]
You need to download the SelectionGAN repo first, and then download the data via the SelectionGAN repo.

**Comment by Eliot04** [comment]
Thank you for your response. Sorry, I mean the checkpoint, I use the following command line:
cd scripts
sh download_xinggan_model.sh

**Comment by Ha0Tang** [comment]
Try:
cd scripts/
sh download_xinggan_model.sh market (create the folder)
sh download_xinggan_model.sh market (download the model)

**Comment by Eliot04** [comment]
Thanks
